export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';

export const APP_LOAD = 'APP_LOAD';

export const REDIRECT = 'REDIRECT';

export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const SIGNUP_PAGE_UNLOADED = 'SIGNUP_PAGE_UNLOADED';
export const SIGNUP_PAGE_LOADED = 'SIGNUP_PAGE_LOADED';
export const ROOMS_PAGE_UNLOADED = 'ROOMS_PAGE_UNLOADED';
export const ROOMS_PAGE_LOADED = 'ROOMS_PAGE_LOADED';
export const YOURROOMS_PAGE_UNLOADED = 'YOURROOMS_PAGE_UNLOADED';
export const YOURROOMS_PAGE_LOADED = 'YOURROOMS_PAGE_LOADED';
export const ROOM_PAGE_UNLOADED = 'ROOM_PAGE_UNLOADED';
export const ROOM_PAGE_LOADED = 'ROOM_PAGE_LOADED';
export const ADD_ROOM = 'ADD_ROOM';

export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const UPDATE_ROOM_AUTH = 'UPDATE_ROOM_AUTH';
export const FIELD_ERROR = 'FIELD_ERROR';
export const ROOM_FIELD_ERROR = 'ROOM_FIELD_ERROR';
export const HANDLE_AJAX_ERROR = 'HANDLE_AJAX_ERROR';

export const CLOSE_ERROR = 'CLOSE_ERROR';
