export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';

export const APP_LOAD = 'APP_LOAD';

export const REDIRECT = 'REDIRECT';

export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const SIGNUP_PAGE_UNLOADED = 'SIGNUP_PAGE_UNLOADED';
export const SIGNUP_PAGE_LOADED = 'SIGNUP_PAGE_LOADED';
export const ROOMS_PAGE_UNLOADED = 'ROOMS_PAGE_UNLOADED';
export const ROOMS_PAGE_LOADED = 'ROOMS_PAGE_LOADED';
export const YOURROOMS_PAGE_UNLOADED = 'YOURROOMS_PAGE_UNLOADED';
export const YOURROOMS_PAGE_LOADED = 'YOURROOMS_PAGE_LOADED';
export const ROOM_PAGE_UNLOADED = 'ROOM_PAGE_UNLOADED';
export const ROOM_PAGE_LOADED = 'ROOM_PAGE_LOADED';
export const ADD_ROOM = 'ADD_ROOM';
export const EDIT_ROOM = 'EDIT_ROOM';
export const BOOK_ROOM = 'BOOK_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';
export const ROOMEDITOR_PAGE_LOADED = 'ROOMEDITOR_PAGE_LOADED';
export const ROOMEDITOR_PAGE_UNLOADED = 'ROOMEDITOR_PAGE_UNLOADED';
export const BOOKINGS_PAGE_LOADED = 'BOOKINGS_PAGE_LOADED';
export const BOOKINGS_PAGE_UNLOADED = 'BOOKINGS_PAGE_UNLOADED';

export const UPDATE_AUTH_FIELD = 'UPDATE_AUTH_FIELD';
export const UPDATE_ROOMEDITOR_FIELD = 'UPDATE_ROOMEDITOR_FIELD';
export const FETCH_GMAPS_RESULTS = 'FETCH_GMAPS_RESULTS';
export const UPDATE_LOCATION_FROM_SUGGESTION = 'UPDATE_LOCATION_FROM_SUGGESTION';
export const UPLOAD_FEATURED_IMAGE = 'UPLOAD_FEATURED_IMAGE';
export const ROOMEDITOR_UPLOAD_ERROR = 'ROOMEDITOR_UPLOAD_ERROR';

export const FIELD_ERROR = 'FIELD_ERROR';
export const ROOM_FIELD_ERROR = 'ROOM_FIELD_ERROR';
export const ROOMEDITOR_FIELD_ERROR = 'ROOMEDITOR_FIELD_ERROR';
export const HANDLE_AJAX_ERROR = 'HANDLE_AJAX_ERROR';

export const CLOSE_ERROR = 'CLOSE_ERROR';
export const INCREMENT_ROOMEDITOR_GUESTS = 'INCREMENT_ROOMEDITOR_GUESTS';
export const DECREMENT_ROOMEDITOR_GUESTS = 'DECREMENT_ROOMEDITOR_GUESTS';
